### ISSUE TITLE
qobuz intégration

### ISSUE THREAD

**Issue by jimsaye** [Migz93/lidarr_smloadr_script#11]
hello,it's possible to have a qobuz intégration
with this tool https://github.com/Sorrow446/Qo-DL ?
or with the api qobuz https://github.com/Qobuz/api-documentation

thank's a lot.

**Comment by theg00s3** [comment]
To be honest, it's unlikely. Qobuz is only available in a select few countries, and it's also a paid service

**Comment by Migz93** [comment]
As theg00s3 has advised, Qobuz isn't something i'd want to implement due to being a restricted and paid service. Sorry.
