### ISSUE TITLE
Lidarr running on Windows

### ISSUE THREAD

**Issue by teenhype902102** [Migz93/lidarr_smloadr_script#12]
Hello. Hoping someone might be able to point me in the right direction. I have Lidarr running on Windows 10, and lidarr_smloadr_script running inside of Bash on the same machine.

Everything seems to work perfectly except for when I have EnableLidarrProcess set to True, which is because the Windows path will be different than the linux mount location.

To overcome this obstacle, I added another variable in the config DownloadDirWin, and changed this in the script to use this path to pass to Lidarr, and Lidarr seems to accept this (and I confirmed that it's showing up in the events under Lidarr) but never actually finds any new files (confirmed there are files being written.)

So in the config I now have:
downloadDir="/mnt/d/Lidarr/"
downloadDirWin="D:\\\\Lidarr"

Thought it worth noting that I escaped this backslash in this variable (so written with 4 backslashes) after some trial and error as I'm not all that familiar with what JSON accepts.

And in the script I did :
dlloc=${downloadDirWin}

Anyone have any ideas? I'm in over my head on this one. 

ALSO: thanks so much to the original author of this script, and the other contributors. Awesome work.

**Comment by theg00s3** [comment]
Could it be a permissions issue?
Could you post your logs from Lidarr when you run SMLoadr?

**Comment by theg00s3** [comment]
Try using wslpath -a "<path in windows>" and it'll give you the proper path for wsl, or you can use wslpath -w "<path in WSL>" to get the proper windows path

**Comment by theg00s3** [comment]
As in just type the command in wsl to find the path and then use that path in the script

**Comment by theg00s3** [comment]
I was actually going to recommend the 4 backslashes, but yeah, I’m not actually sure why it doesn’t work. I’ll set up Lidarr on my laptop to see if I can replicate the issue

________________________________

**Comment by theg00s3** [comment]
Yeah I'm not sure why it doesn't work. It's definitely got to do with WSL and windows using a backslash instead of a forward slash

**Comment by permutationalparody** [comment]
Created a pull request with the necessary changes, please test.
Make sure the path in the config file is not a windows path and EnableWSLmode=True, the script will take care of translating the path into a windows path.
[https://github.com/permutationalparody/lidarr_smloadr_script](url)

**Comment by teenhype902102** [comment]
Updated the script and config, but no luck. It makes it seem like everything is working properly, but it's as if it doesn't see any files in the download folder. If I go to the artist and hit refresh, it immediately finds the files and updates the library. I feel like I'm overlooking something dumb.

https://www.dropbox.com/s/2rfcfn5gnlti26y/lidar-task-screenshot.png?dl=0

Log:
19-9-5 21:12:55.5|Info|Database|Vacuuming Log database
19-9-5 21:12:55.5|Info|Database|Log database compressed

**Comment by permutationalparody** [comment]
Can you post your system/events log from within lidarr (remember to select filter all)?
to dump the exact command sent to the lidarr api type the ffg after line 214:
echo "${LidarrProcessIt}"

**Comment by teenhype902102** [comment]
Sorry, this is probably over my head. I have zero clue what you are talking about. I also didn't realize I had options for ubuntu versions - I installed whatever the Windows store gave. 
I think I'm just going to go about this another route. I've lost interest in Lidarr as a result, but I appreciate all of your help.

**Comment by permutationalparody** [comment]
No problem.

**Comment by Migz93** [comment]
Thanks for the fix permutationalparody. I'll see if i can setup a test environment to try this out.

**Comment by Migz93** [comment]
Confirmed permutationalparodys PR #14 allows the script to work under WSL with Lidarr running on Windows.
WSL for Ubuntu 18.04 & Ubuntu 16.04 tested successfully.

**Comment by neFAST** [comment]
Is it possible to get this working on windows _without_ WSL?

**Comment by Migz93** [comment]
The original version of the script was written in powershell and is still available under the legacy folder. Although this only grabbed everything by an artist that's available on deezer, no option for only looking for albums that are monitored in Lidarr.
The likelyness of porting the latest version of the script into powershell to run natively on windows is pretty slim, feel free to fork the project and make the changes yourself.
