### ISSUE TITLE
Script Timeout

### ISSUE THREAD

**Issue by teenhype902102** [Migz93/lidarr_smloadr_script#13]
Every once in a while I'll run into an issue where the SMLoader indicates it's connecting to the Deezer API, or it'll say something about processing or I've one where it just hangs at 99% and nothing else happens and I've left it there for hours with no avail. Starting the script over again isn't ideal in my case (processing thousands of artists), so in case it helps someone else out, I added this workaround which seems to work at line 96 of my script:

timeout 900s ./SMLoadr-linux-x64 -q ${quality} -p "${downloadDir}" "${DLURL}" 

I made the timeout quite large as I have run into a couple situations where a couple of artist had something like 5000 tracks? and it took some serious time and I didn't want it to kill the script prematurely, and for me waiting 15 minutes is still much better than starting over from scratch and spending something like 24 hours to catch back up to where I left off.

**Comment by theg00s3** [comment]
I believe that this is an SMLoadr issue, there's an issue [here](https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr/issues/40)

**Comment by Migz93** [comment]
Hi,

Thanks for providing that workaround. I'll see if i can include it in the script.

**Comment by Migz93** [comment]
Added the timeout function to the script, set timeout within the config file, default is 5 minutes.
#18
