### ISSUE TITLE
redirection unexpected

### ISSUE THREAD

**Issue by D347HxD** [Migz93/lidarr_smloadr_script#16]
I am getting this error when trying to run the script:
https://bss.nz/i/09-11-2019-c59OTBAmTQ.png

**Comment by permutationalparody** [comment]
What version of linux are you running?
It looks like you're running the script using the sh shell. use the ffg instead to start the script with bash:
`sudo bash lidarr-smloadr.sh`

**Comment by D347HxD** [comment]
This solved the issue I was having, I was running Ubuntu 18.04 for reference

My suggestion would be to include this in the readme, regardless this issue will be here for future people who run across this :)
