### ISSUE TITLE
Make lidarr_smloadr_script compatible with d-fi

### ISSUE THREAD

**Issue by topdollar3** [Migz93/lidarr_smloadr_script#23]
Hello there,
First of all, thank you very much for your script, it works realy great at least for me.

I would like to ask if you can make your script compatible with d-fi, a new smloadr style deezer downloader.
https://notabug.org/sayem314/d-fi
The way d-fi work is pretty much the same as smloadr, but i found that d-fi is more reliable (smloadr get stuck alot if you use it to download a lot of music at the same time).

Thanks

**Comment by Migz93** [comment]
Hi,

We might put it in as an option to configure which download executable to use, although if we start having options for everything the config file will get wild so will think about it.

Although It looks like d-fi accepts the same parameters as smloadr, so it's a pretty simple change if you want to do it yourself. Just change line 88 to use the d-fi executable.
From this
`timeout $Timeout ./SMLoadr-linux-x64 -q ${Quality} -p "${DownloadDir}" "${DLURL}"`

To something like this:
`timeout $Timeout ./d-fi -q ${Quality} -p "${DownloadDir}" "${DLURL}"`

Let me know how you get on with the manual change.

**Comment by RandomNinjaAtk** [comment]
Just an FYI, we have a new update in the works that uses d-fi... so #soon

**Comment by RandomNinjaAtk** [comment]
Posted d-fi update to develop branch for testing: https://github.com/Migz93/lidarr_smloadr_script/tree/develop
