### ISSUE TITLE
Plex_Autoscan AppProcess?

### ISSUE THREAD

**Issue by Arg0t** [Migz93/lidarr_smloadr_script#24]
Any chance you could implement curl to plex autoscan on completion of an artist download?

Tried changing the LidarrProcessIt to 
`LidarrProcessIt=$(curl -d "eventType=Manual&filepath=/mnt/unionfs/Media/Music/${LidArtistName}" $PlexAutoScanURL);`

but that just results in Autoscan getting spammed by requests rather than one request.

**Comment by Migz93** [comment]
Why not let Lidarr import the files (Which is what i assume you're already doing if you're using the "LidarProcessIt") and then configure Lidarr to notify PAS?

**Comment by Arg0t** [comment]
Really just using Lidarr as an artist list rather than have it import. Have script set to grab artist not album which results in files that lidarr would not import.
Just looking to grab the artist directly into unionfs and notify plex to scan it.

I think I have it working by using Lidarr path, Artist Name doesnt always match folder or case.

```LidPath=$(echo "${wantit}" | jq -r .[$i].path)```

Then a new process section

```PlexAutoScanProcess(){
	logit "Sending to Plex Autoscan for post processing $lidpath"
		PlexAutoScanProcessIt=$(curl -d "eventType=Manual&filepath=$LidPath" $PlexAutoScanURL);
	sleep 3s
}```

Just need to test it a bit more.
