### ISSUE TITLE
invalid character filtering

### ISSUE THREAD

**Issue by orsomething1030** [Migz93/lidarr_smloadr_script#26]
Problem:
Added Ladytron album Best of 00–10 as wanted in Lidarr.
Run script and no match found through perfect or fuzzy matching.  There is a perfect match however on deezer except for one character.
The hyphen (not really hyphen, but looks like it) in the album title is a non-standard character in musicbrainz, and is used by Lidarr.  Not sure if this is allowed or is a bug on either musicbrainz or Lidarr's part.

Desired solution:
I edited the script to strip - and – from the deezer and lidarr album titles and got a perfect match and it imported correctly.  It would be nice to have the script updated to eliminate or ignore non-standard characters when matching.

**Comment by Migz93** [comment]
Something for us to look into, thank you for raising it

**Comment by RandomNinjaAtk** [comment]
If you wrote an edit to make it work, could you create a pull request or post the code change to this thread?

**Comment by RandomNinjaAtk** [comment]
Also on another note, give the latest code a try and see if you change can be implemented in it: https://github.com/Migz93/lidarr_smloadr_script/tree/develop

**Comment by orsomething1030** [comment]
I haven't tried the develop branch, but here's the code:

LidAlbumName=$(echo "${wantit}" | jq -r .records[${i}].title | tr '[:upper:]' '[:lower:]' | tr -cd '[:print:]' | tr -d '[:punct:]' | tr -s '[:space:]' )  

DeezerDiscogAlbumName=$(echo "${DeezerDiscog}" |jq ".[]|.[$x]?"|jq -r .title | tr '[:upper:]' '[:lower:]' | tr -cd '[:print:]' | tr -d '[:punct:]' | tr -s '[:space:]' )  

I haven't tested it much and make no claims as to how it works across languages and all the weird album names out there.  I haven't looked into whether this would help with artist names either.

**Comment by RandomNinjaAtk** [comment]
Give this a shot on the dev branch, and if it goes well, maybe write a PR for the change?
