### ISSUE TITLE
What does it download?

### ISSUE THREAD

**Issue by theg00s3** [Migz93/lidarr_smloadr_script#3]
I was just wondering, does this just download what albums/EPs/singles are wanted in Lidarr, or does it just download everything? For example, my lidarr setup only wants albums and EPs. Does this download the singles as well?

**Comment by Migz93** [comment]
Hi theg00s3.

Sorry for the delayed reply, i thought i'd get a notification if anything happened on git. Your reddit comment made me check here.

You already know the answer but for anyone else that may come here, this script at the moment downloads everything by that artist. I'll be looking at getting it to only download whatever is actually monitored in Lidarr.

**Comment by Migz93** [comment]
Being able to only look for and download wanted albums/EPs/singles is now part of the script, part of PR #6 
All thanks to @permutationalparody for his modified version of the script.
